foreground            #e4e2e1
background            #131313
selection_foreground  #293233
selection_background  #bec8c9
url_color             #d8c2b9
cursor                #bec8c9
cursor_text_color     #293233

color0   #131313
color1   #ffb4ab
color2   #bec8c9
color3   #d8c2b9
color4   #bec8c9
color5   #d8c2b9
color6   #7c6a63
color7   #e4e2e1

color8   #8d9292
color9   #ffb4ab
color10  #bec8c9
color11  #d8c2b9
color12  #bec8c9
color13  #d8c2b9
color14  #7c6a63
color15  #e4e2e1

tab_bar_background              #131313
tab_bar_margin_color            #131313
active_tab_foreground           #293233
active_tab_background           #bec8c9
inactive_tab_foreground         #c3c7c8
inactive_tab_background         #131313
