foreground            #e0e3e4
background            #101415
selection_foreground  #00363e
selection_background  #7dd3e4
url_color             #ffb77a
cursor                #7dd3e4
cursor_text_color     #00363e

color0   #101415
color1   #ffb4ab
color2   #7dd3e4
color3   #ffb77a
color4   #7dd3e4
color5   #ffb77a
color6   #9e6229
color7   #e0e3e4

color8   #889395
color9   #ffb4ab
color10  #7dd3e4
color11  #ffb77a
color12  #7dd3e4
color13  #ffb77a
color14  #9e6229
color15  #e0e3e4

tab_bar_background              #101415
tab_bar_margin_color            #101415
active_tab_foreground           #00363e
active_tab_background           #7dd3e4
inactive_tab_foreground         #bec8cb
inactive_tab_background         #101415
